config/routes.rb
Rails.application.routes.draw do

  
resources 'posts'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
#1. 우리가 쓴 글들을 다 볼 수 있는 페이지
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def create
    # @post = Post.new
    # @post.title = params[:title]
    # @post.content = params[:content]
    # @post.save
    # Form_tag 전용
    # Post.create(title: params[:title], content: params[:content])
    
    # Form_for 전용
    Post.create(title: params[:post][:title], content: params[:post][:content])
    
    redirect_to '/posts' #Method Get
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    # Form_tag 전용
    # @post.update_attributes(title: params[:title], content: params[:content])
    
    # Form_for 전용
    @post.update_attributes(title: params[:post][:title], content: params[:post][:content])
    redirect_to '/posts'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to '/posts'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%#= form_tag post_path(@post.id), method: 'patch' do %>
  <%#= text_field_tag 'title', @post.title %>
  <%#= text_area_tag 'content', @post.content %>
  <%#= submit_tag 'Submit!' %>
<%# end %>

<%= form_for @post do |f| %>
  <%= f.text_field 'title' %>
  <%= f.text_area 'content' %>
  <%= f.submit 'Submit!' %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div>
    <%= post.id %>
    <%= post.title %>
    <%= post.content %>
    <%= link_to '이 글 보기', post_path(post.id) %>
    <%= link_to '이 글 수정', edit_post_path(post.id) %>
    <%= link_to '이 글 삭제', post_path(post.id), method: 'delete', data: {confirm: "정말 삭제하실 건가요?"} %>
  </div>
<% end %>

<%= link_to '새 글쓰기', '/posts/new'  %>

app/views/posts/new.html.erb
<%#= form_tag posts_path, method: 'post' do %>
  <%#= text_field_tag 'title' %>
  <%#= text_area_tag 'content' %>
  <%#= submit_tag 'Submit!' %>
<%# end %>

<%= form_for @post do |f| %>
  <%= f.text_field 'title' %>
  <%= f.text_area 'content' %>
  <%= f.submit 'Submit!' %>
<% end %>

app/views/posts/show.html.erb
<%= @post.id %>
<p>
  <%= @post.title %>
</p>
<p>
  <%= @post.content %>
</p>

<%= link_to "Back", :back %>